# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.define "node1", primary: true do |v|
        v.vm.box =  "generic/ubuntu/2204"
        v.vm.network "private_network", ip: "192.168.xx.x4"
        v.vm.synced_folder ".", "/vagrant", disabled: true
        v.vm.hostname = "node1"

        v.vm.provider "virtualbox" do |vb|
            vb.memory = 2048
            vb.name = "node1"
        end
    end

    config.vm.define "node2" do |v|
        v.vm.box = "generic/rocky9"
        v.vm.network "public_network", bridge: "BRIDGE"
        v.vm.synced_folder ".", "/vagrant", disabled: true
        v.vm.hostname = "node2"
    end

end